[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python start.py"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
PYTHONUNBUFFERED = "1"
STREAMLIT_SERVER_HEADLESS = "true"
LOG_LEVEL = "INFO"
EMBEDDING_MODEL = "all-MiniLM-L6-v2"
COLLECTION_NAME = "documenter"
MODEL_N_CTX = "4096"
MODEL_N_GPU_LAYERS = "0"