batch_size: 100
cache_size: 200
cache_ttl: 3600
chunk_overlap: 200
chunk_size: 1000
connection_timeout: 30
context_window: 4096
default_k: 5
enable_gpu: false
max_k: 10
max_retries: 3
max_tokens: 512
memory_limit_gb: 8.0
mmr_lambda: 0.7
num_threads: 4
quality_threshold: 50.0
similarity_threshold: 0.7
temperature: 0.1
